<?php

class Treffend_Cookies_ACF
{

    public static function init()
    {
        if (!class_exists('ACF')) {
            return;
        }

        // Add ACF-specific functionality here
        add_action('acf/include_fields', function () {
            if (! function_exists('acf_add_local_field_group')) {
                return;
            }

            acf_add_local_field_group(array(
                'key' => 'group_66bc9946034dc',
                'title' => 'Cookie options',
                'fields' => array(
                    array(
                        'key' => 'field_66bc9946a613c',
                        'label' => 'Code',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'selected' => 0,
                    ),
                    array(
                        'key' => 'field_66bc9954a613d',
                        'label' => 'Inside head code',
                        'name' => 'treffend_cookie-code_head',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_66bc9967a613e',
                        'label' => 'Top body code',
                        'name' => 'treffend_cookie-code_top_body',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_66bc9974a613f',
                        'label' => 'Bottom body code',
                        'name' => 'treffend_cookie-code_bottom_body',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_66bc9985a6140',
                        'label' => 'Cookie banner',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'selected' => 0,
                    ),
                    array(
                        'key' => 'field_66c3083bb0d9c',
                        'label' => 'Banner style',
                        'name' => 'treffend_cookie-banner_style',
                        'aria-label' => '',
                        'type' => 'select',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'choices' => array(
                            'banner-right_bottom' => 'Bottom right',
                            'banner-left_bottom' => 'Bottom left',
                            'bar-bottom' => 'Bottom full width',
                        ),
                        'default_value' => 'banner-right_bottom',
                        'return_format' => 'value',
                        'multiple' => 0,
                        'allow_null' => 0,
                        'ui' => 0,
                        'ajax' => 0,
                        'placeholder' => '',
                    ),
                    array(
                        'key' => 'field_66bc9995a6141',
                        'label' => 'Banner title',
                        'name' => 'treffend_cookie-banner_title',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_66bc99b0a6142',
                        'label' => 'Text',
                        'name' => 'treffend_cookie-banner_text',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_66bc99c7a6143',
                        'label' => 'Accept button title',
                        'name' => 'treffend_cookie-button_accept',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_66bc99e7a6144',
                        'label' => 'Decline button title',
                        'name' => 'treffend_cookie-button_decline',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_cookie_dev_mode',
                        'label' => 'Development Mode',
                        'name' => 'treffend_cookie-dev_mode',
                        'aria-label' => '',
                        'type' => 'true_false',
                        'instructions' => 'Enable this to always show the cookie banner (useful for styling and development)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'message' => 'Enable development mode',
                        'default_value' => 0,
                        'ui' => 1,
                        'ui_on_text' => 'Enabled',
                        'ui_off_text' => 'Disabled',
                    ),
                    array(
                        'key' => 'field_cookie_privacy_link',
                        'label' => 'Privacy Policy Link',
                        'name' => 'treffend_cookie-privacy_link',
                        'aria-label' => '',
                        'type' => 'link',
                        'instructions' => 'Link to your privacy policy page (required for Dutch law compliance)',
                        'required' => 1,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => '',
                        'placeholder' => 'https://example.com/privacy',
                    ),
                    array(
                        'key' => 'field_cookie_policy_link',
                        'label' => 'Cookie Policy Link',
                        'name' => 'treffend_cookie-cookie_policy_link',
                        'aria-label' => '',
                        'type' => 'link',
                        'instructions' => 'Link to your cookie policy page (optional but recommended)',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '50',
                            'class' => '',
                            'id' => '',
                        ),
                        'return_format' => 'array',
                    ),
                    array(
                        'key' => 'field_cookie_modal_tab',
                        'label' => 'Cookie Settings Modal',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'selected' => 0,
                    ),
                    array(
                        'key' => 'field_cookie_modal_title',
                        'label' => 'Modal Title',
                        'name' => 'treffend_cookie-modal_title',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Cookie Instellingen',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_cookie_modal_description',
                        'label' => 'Modal Description',
                        'name' => 'treffend_cookie-modal_description',
                        'aria-label' => '',
                        'type' => 'textarea',
                        'instructions' => 'Introduction text shown in the cookie settings modal',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Kies welke cookies u wilt accepteren. U kunt uw voorkeuren op elk moment wijzigen.',
                        'tabs' => 'all',
                        'toolbar' => 'full',
                        'media_upload' => 1,
                        'delay' => 0,
                    ),
                    array(
                        'key' => 'field_cookie_button_settings',
                        'label' => 'Settings Button Text',
                        'name' => 'treffend_cookie-button_settings',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Text for the "Cookie Settings" button',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Cookie Instellingen',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_cookie_button_save',
                        'label' => 'Save Button Text',
                        'name' => 'treffend_cookie-button_save',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Text for the "Save" button in modal',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Opslaan',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_cookie_button_accept_all',
                        'label' => 'Accept All Button Text',
                        'name' => 'treffend_cookie-button_accept_all',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Text for the "Accept All" button in modal',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Alles Accepteren',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_cookie_button_reject_all',
                        'label' => 'Reject All Button Text',
                        'name' => 'treffend_cookie-button_reject_all',
                        'aria-label' => '',
                        'type' => 'text',
                        'instructions' => 'Text for the "Reject All" button in modal',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '33',
                            'class' => '',
                            'id' => '',
                        ),
                        'default_value' => 'Alles Weigeren',
                        'maxlength' => '',
                        'placeholder' => '',
                        'prepend' => '',
                        'append' => '',
                    ),
                    array(
                        'key' => 'field_cookie_categories_tab',
                        'label' => 'Cookie Categories',
                        'name' => '',
                        'aria-label' => '',
                        'type' => 'tab',
                        'instructions' => '',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'placement' => 'left',
                        'endpoint' => 0,
                        'selected' => 0,
                    ),
                    array(
                        'key' => 'field_cookie_category_analytics',
                        'label' => 'Analytics Category',
                        'name' => 'treffend_cookie-category_analytics',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => 'Configure the Analytics cookie category',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_cookie_category_analytics_title',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'default_value' => 'Analytics',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_cookie_category_analytics_description',
                                'label' => 'Description',
                                'name' => 'description',
                                'type' => 'textarea',
                                'default_value' => 'Deze cookies helpen ons te begrijpen hoe bezoekers onze website gebruiken door informatie te verzamelen en te rapporteren.',
                                'rows' => 3,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_cookie_category_marketing',
                        'label' => 'Marketing Category',
                        'name' => 'treffend_cookie-category_marketing',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => 'Configure the Marketing cookie category',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_cookie_category_marketing_title',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'default_value' => 'Marketing',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_cookie_category_marketing_description',
                                'label' => 'Description',
                                'name' => 'description',
                                'type' => 'textarea',
                                'default_value' => 'Deze cookies worden gebruikt om advertenties te tonen die relevant zijn voor u en uw interesses.',
                                'rows' => 3,
                            ),
                        ),
                    ),
                    array(
                        'key' => 'field_cookie_category_preferences',
                        'label' => 'Preferences Category',
                        'name' => 'treffend_cookie-category_preferences',
                        'aria-label' => '',
                        'type' => 'group',
                        'instructions' => 'Configure the Preferences cookie category',
                        'required' => 0,
                        'conditional_logic' => 0,
                        'wrapper' => array(
                            'width' => '',
                            'class' => '',
                            'id' => '',
                        ),
                        'layout' => 'block',
                        'sub_fields' => array(
                            array(
                                'key' => 'field_cookie_category_preferences_title',
                                'label' => 'Title',
                                'name' => 'title',
                                'type' => 'text',
                                'default_value' => 'Voorkeuren',
                                'placeholder' => '',
                            ),
                            array(
                                'key' => 'field_cookie_category_preferences_description',
                                'label' => 'Description',
                                'name' => 'description',
                                'type' => 'textarea',
                                'default_value' => 'Deze cookies onthouden uw voorkeuren en instellingen om uw ervaring te personaliseren.',
                                'rows' => 3,
                            ),
                        ),
                    ),
                ),
                'location' => array(
                    array(
                        array(
                            'param' => 'options_page',
                            'operator' => '==',
                            'value' => 'cookie-options',
                        ),
                    ),
                ),
                'menu_order' => 0,
                'position' => 'normal',
                'style' => 'seamless',
                'label_placement' => 'top',
                'instruction_placement' => 'label',
                'hide_on_screen' => '',
                'active' => true,
                'description' => '',
                'show_in_rest' => 0,
            ));
        });

        add_action('acf/init', function () {
            acf_add_options_page(array(
                'page_title'  => 'Cookies',
                'menu_slug'   => 'cookie-options',
                'position'    => '',
                'parent_slug' => 'options-general.php', // This places the page under "Settings"
                'redirect'    => false,
                'description' => 'Change the cookie settings',
                'menu_icon'   => array(
                    'type'  => 'dashicons',
                    'value' => 'dashicons-info',
                ),
                'icon_url'    => 'dashicons-info',
            ));
        });
    }
}
